"""Updated for 2fa

Revision ID: 0f78809ea4cc
Revises: 
Create Date: 2024-12-16 20:37:05.521501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f78809ea4cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transaction', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Staff', ['s_id'], ['s_ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
