"""Added password field to staff

Revision ID: 663b9fcca6b7
Revises: 
Create Date: 2024-12-10 09:09:42.838041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663b9fcca6b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Staff', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
