"""minor update

Revision ID: 935923d042b3
Revises: 0f78809ea4cc
Create Date: 2024-12-16 21:05:51.086270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935923d042b3'
down_revision = '0f78809ea4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Staff', schema=None) as batch_op:
        batch_op.alter_column('two_factor_secret',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Staff', schema=None) as batch_op:
        batch_op.alter_column('two_factor_secret',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
